source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass', '~> 3.3.3'
gem 'twitter-bootstrap-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'tzinfo-data'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'font-awesome-rails'
gem 'font-awesome-sass'
gem 'haml-rails'
gem 'simple_form'
gem 'cocoon'

#profiles
gem 'devise'
gem 'omniauth'
gem 'carrierwave'

group :development, :test do
  gem 'awesome_print'
  gem 'rspec-rails'
  gem 'rspec_junit_formatter'
  gem 'cucumber-rails', :require => false
  gem 'spring'
  gem 'better_errors'
  gem 'pry'
  gem 'pry-nav'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
end

group :production do
  gem 'pg'
end
