source 'https://rubygems.org'


gem 'rails', '4.1.8'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem "therubyracer"
gem "less-rails"
gem "twitter-bootstrap-rails"
gem "font-awesome-rails"
gem "haml-rails"

group :development, :test do
  gem "spring"
  gem "better_errors"
  gem "pry"
end


