Community.create(name: "Science and Technology", description: "")
Community.create(name: "Automotive", description: "")
Community.create(name: "Sports", description: "")
Community.create(name: "Health", description: "")
Community.create(name: "Education", description: "")